---
- name: Create AWS EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    hosts:
      - build
      - prod


  tasks:
  - name: Create securiy group with port 22 and 8080 open to 0.0.0.0/0
    ec2_group:
      name: EC2SecGroup
      description: security grop for build and prod instance
      region: eu-central-1
      rules:
        - proto: tcp
          ports:
            - 22
            - 8080
          cidr_ip: 0.0.0.0/0

  - name: Create EC2 instance
    ec2:
      instance_type: t2.micro
      image: ami-05f7491af5eef733a
      wait: yes
      group: EC2SecGroup
      region: eu-central-1
      instance_tags:
        Name: '{{ item }}'
    loop: '{{ hosts }}'

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.instances[0].public_ip }}"
      groupname: '{{ hosts }}'
    loop: "{{ ec2.results }}"

  - name: Wait for SSH to come up
    delegate_to: "{{ item.instances[0].public_dns_name }}"
    wait_for_connection:
      delay: 60
      timeout: 320
    loop: "{{ ec2.results }}"

      #assign_public_ip: yes
