pipeline {
  agent any

  stages {
    stage ('clone git repo') {
      steps {
        git 'https://github.com/OMironyuk/DevSchool.git'
      }
    }
    stage('TF Init&Plan') {
      steps {
        sh 'terraform init'
        sh 'terraform plan'
        sh 'terraform apply -auto-approve'
      }
    }
  }
}