---
- name: Preparing for connection to ec2_instances
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Add new instance to host group
    add_host:
      hostname: "{{ item }}"
      groupname: build
    with_file: "ec2_build_public_ip"
    register: build_ip

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item }}"
      groupname: prod
    with_file: "ec2_prod_public_ip"
    register: prod_ip

#  - name: Check hostname
#    debug: msg= "{{ build_ip }}"

  - name: Wait for ssh server to be running on created instances
    wait_for:
      host: "{{ item.add_host.host_name }}"
      port: 22
      search_regex: OpenSSH
    loop: "{{ build_ip.results | union (prod_ip.results) }}"

  - name: "Retrieve an authentication token"
    command: "aws ecr get-login-password --region {{aws_region}}"
    register: awsrepo

  - name: Get the current caller identity information
    aws_caller_info:
    register: caller_info

  - name: Create ECR repository
    ecs_ecr:
      name: solitaire

- name: Create build image
  hosts: build
  remote_user: ubuntu
  become: yes
  gather_facts: false

  tasks:
  - name: Ensure required packages is present
    apt:
      name:
        - python3
        - python3-pip
        - docker.io
      state: present
      update_cache: yes

  - name: Enshure Docker SDK for Python is present
    pip:
      name: docker
      state: present

  - name: Create build directory
    file:
      path: /home/user/build-image
      state: directory

  - name: Copy Dockerfile
    copy:
      src: ./build-image/Dockerfile
      dest: /home/user/build-image/

  - name: docker login
    docker_login:
      registry_url: "{{hostvars['localhost']['caller_info'].account}}.dkr.ecr.{{aws_region}}.amazonaws.com"
      username: AWS
      password: "{{hostvars['localhost']['awsrepo'].stdout}}"

  - name: Build an image
    docker_image:
      path: /home/user/build-image/
      name: "{{hostvars['localhost']['caller_info'].account}}.dkr.ecr.{{aws_region}}.amazonaws.com/solitaire:v1"
      push: yes

- name: Create prod image
  hosts: prod
  remote_user: ubuntu
  become: yes
  gather_facts: false

  tasks:
  - name: Ensure required packages is present
    apt:
      name:
        - python3
        - python3-pip
        - docker.io
      state: present
      update_cache: yes

  - name: Enshure Docker SDK for Python is present
    pip:
      name: docker
      state: present

  - name: Docker login
    docker_login:
      registry_url: "{{hostvars['localhost']['caller_info'].account}}.dkr.ecr.{{aws_region}}.amazonaws.com"
      username: AWS
      password: "{{hostvars['localhost']['awsrepo'].stdout}}"

  - name: Run container
    docker_container:
      name: solitaire
      image: "{{hostvars['localhost']['caller_info'].account}}.dkr.ecr.{{aws_region}}.amazonaws.com/solitaire:v1"
      ports:
        - "8080:8080"
      state: started
