---
- name: change index.html
  hosts: nginx
  become: yes

  tasks:
    - name: Ensure nginx present
      apt:
        name: nginx
        state: present

    - name: Change index.html
      lineinfile:
        path: /var/www/html/index/html
        regexp: '^'
        line: <p><script> document.write (new Date().toLocaleDateString()); </script></p>