---
# tasks file for app
- name: Ensure package is present
  apt:
    name: default-jre
    state: present

- name: Create tomcat directory
  file:
    path: "{{tomcat_dir}}"
    state: directory

- name: Unarchive Tomcat
  unarchive:
    src: https://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
    dest: "{{tomcat_dir}}"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: Copy tomcat.service
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
  notify:
    - daemon-reload

- name: Transfer artifact from Build to App
  synchronize:
    src: /home/user/Solitaire/target/solitaire-1.1-SNAPSHOT.war
    dest: "{{tomcat_dir}}/webapps/solitaire.war"
  delegate_to: "{{ item }}"
  loop: "{{ groups['build'] }}"
  notify:
    - restart tomcat


