---
- name: install Docker
  hosts: 'build:app'
  become: yes

  tasks:

  - name: Ensure python3 is present
    apt:
      name: python38
      state: present

  - name: Ensure python-pip is apsent
    apt:
      name: python-pip3
      state: present

  - name: Enshure Docker SDK for Python is present
    pip:
      name: docker
      state: present

  - name: Enshure docker package is present
    apt:
      name: docker.io
      state: present

- name: create build image
  hosts: build
  become: yes

  tasks:
    - name: create build directory
      file:
        path: /home/user/build-image
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: copy Dockerfile
      copy:
        src: ./build-image
        dest: /home/user/build-image/Dockerfile
        owner: root
        group: root
        mode: '0644'

    - name: Build an image
      docker_image:
        path: /home/user/build-image/
        name: build_image
    - name: Start container
      docker_container:
        name: app
        image: build_image
        state: started
