___
- name: install Docker
  hosts: 'build:app'
  become: yes

  tasks:
  - name: Enshure docker package is present
    apt:
      name: docker.io
      state: present

- name: create build image
  hosts: build
  become: yes

  tasks:
    - name: Build an image and push it to a private repo
      docker_image:
        path: ./build-image
        name: build_image
    - name: Start container
      docker_container:
        name: app
          image: build_image
          state: started
