---
- name: Build solitaire
  hosts: build
  become: yes

  tasks:
  - name: Ensure maven is present
    apt:
      name: maven
      state: present

  - name: Ensure default-jdk is present
    apt:
      name: default-jdk
      state: present

  - name: Git clone repo
    git:
     repo: https://github.com/Artur-/Solitaire.git
     dest: /home/user/Solitaire

  - name: Create maven artifact
    shell: mvn package
    args:
      chdir: /home/user/Solitaire

  - name: Copy artifact from Build to local
    fetch:
      src: /home/user/Solitaire/target/solitaire-1.1-SNAPSHOT.war
      dest: /home/user/solitaire.war
      flat: yes


- name: Run Solitaire
  hosts: app
  become: yes

  tasks:
  - name: Ensure default-jre is present
    apt:
      name: default-jre
      state: present

  - name: Create tomcat directory
    file:
      path: /usr/local/tomcat
      state: directory

  - name: Unarchive Tomcat
    unarchive:
      src: https://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
      dest: /usr/local/tomcat
      extra_opts: [--strip-components=1]
      remote_src: yes

  - name: Generate ssh key
    openssh_keypair:
      path: /root/.ssh/id_ssh_rsa

  - name: Set authorized key, removing all the authorized keys already set
    authorized_key:
      user: root
      key: '{{ item }}'
      state: present
    delegate_to: build


  - name: Transfer file from build to app
    synchronize:
      src: /home/user/Solitaire/target/*.war
      dest: /usr/local/tomcat/webapps/solitaire.war
    delegate_to: build

  - name: Run tomcat
    command: nohup /usr/local/tomcat/bin/startup.sh