pipeline {
    agent {
        docker {
        image '10.129.0.41:8111/jenkins-agent'
        registryUrl 'http://10.129.0.41:8111'
        registryCredentialsId '1a5ec3e3-b900-493e-84c5-f58edf9ee355'
        args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    tools {
        maven "m3"
    }
    stages {
        stage ('clone git repo') {
            steps {
                git 'https://github.com/OMironyuk/Solitaire.git'
            }
        }
        stage ('Build war'){
            steps {
            sh 'mvn package'
            }
        }
        stage ('Make docker image') {
            steps {
                sh 'docker build -t solitaire:v1 .'
                sh 'docker tag solitaire:v1 10.129.0.41:8111/solitaire:v1  && docker push 10.129.0.41:8111/solitaire:v1'
            }
        }
    }
}