---
# tasks file for build
- name: Generate ssh key
  openssh_keypair:
    лкнowner: root
    path: /root/.ssh/id_rsa
  register: keypair

- name: Set authorized key taken from file
  authorized_key:
    user: root
    state: present
    key: "{{ keypair.public_key }}"
  delegate_to: "{{host_name}}"

