---
# tasks file for build
- name: Generate ssh key
  openssh_keypair:
    owner: root
    path: /root/.ssh/id_rsa

- name: Set authorized key taken from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  delegate_to: "{{host_name}}"

