---
# tasks file for build
- name: Generate ssh key
  openssh_keypair:
    owner: root
    path: /root/.ssh/id_rsa
  register: keypair

- name: Check hostname
  debug: msg="{{ delegate_host }}"


- name: Set authorized key taken from file
  authorized_key:
    user: root
    state: present
    key: "{{ keypair.public_key }}"
  delegate_to: "{{item}}"
  loop: "{{ groups[delegate_host] }}"
