---
version: '3.8'
services:
  buildimage:
    build:
      context: ./build-image
    volumes:
      - type: volume
        source: share
        target: /home/user/Solitaire/target/

  app:
    build:
      context: ./final-image
    volumes:
      - type: volume
        source: share
        target: /usr/local/tomcat/webapps/
    ports:
        - "8080:8080"

volumes:
  share: