---
# tasks file for docker
- name: Ensure required packages for Docker are present
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python3
    - python3-pip
    - docker
    - docker.io

