---
# tasks file for docker
- name: Ensure python3 is present
  apt:
    name: python3
    state: present

- name: Ensure python3-pip is present
  apt:
    name: python3-pip
    state: present

- name: Enshure Docker SDK for Python is present
  pip:
    name: docker
    state: present

- name: Enshure docker package is present
  apt:
    name: docker.io
    state: present
