---
# tasks file for app
- name: Ensure package is present
  apt:
    name: default-jre
    state: present

- name: Create tomcat directory
  file:
    path: "{{tomcat_dir}}"
    state: directory

- name: Unarchive Tomcat
  unarchive:
    src: https://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
    dest: "{{tomcat_dir}}"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: Transfer artifact from Build to App
  copy:
    src: /home/user/solitaire.war
    dest: "{{tomcat_dir}}/webapps/"
  notify:
    - restart tomcat

- name: Run tomcat
  command: nohub "{{tomcat_dir}}/bin/startup.sh" #nohup
