---
- name: Build app
  hosts: build
  become: yes

  roles:
    - build
    - role: ssh_auth
      vars:
        delegate_host: app

- name: Run app
  hosts: app
  become: yes

  roles:
    - app
    - role: ssh_auth
      vars:
        delegate_host: build

